//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feetup.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.Category = new HashSet<Category>();
        }
    
        public int AdminID { get; set; }
        [DisplayName("Admin Name")]
        [Required(ErrorMessage = "This is a required field")]
        public string AdminName { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This is a required field")]
        public string AdminPassword { get; set; }
        public string LoginErrorMessage { get;  set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
        
    }
}
