//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feetup.Models
{
    using System;
    using System.Web;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int ProductID { get; set; }
        [Required]
        public string ProductName { get; set; }
        [Required]
        [Display(Name = "Product Description")]
        public string ProductDescription { get; set; }
        public Nullable<int> CustomerID { get; set; }
        [Required]
        [Display(Name = "Product Price")]
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SellerID { get; set; }

        [Required]
        [Display(Name = "Product Color")]
        public string ProductColor { get; set; }

        [Required]
        [Display(Name = "Product Image")]
        public string ProductImage { get; set; }

        [Required]
        [Display(Name = "Product Brand")]
        public string ProductBrand { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Seller Seller { get; set; }

        
    }
}
